version: "3"
services:
  app:
    image: nimlang/nim:latest
    container_name: nim_playground
    environment:
      TZ: 'Asia/Tokyo'
    working_dir: /usr/src
    # ports:
    #   - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
